familybudget/apps/budgets/urls.py
app_name = "budgets"

urlpatterns = [

]

familybudget/apps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from apps.users.views import RegisterView

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            next_page=reverse_lazy("home"),
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page=reverse_lazy("users:login")),
        name="logout",
    ),
]

familybudget/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("users/", include("apps.users.urls")),
    path("budgets/", include("apps.budgets.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

familybudget/apps/budgets/models.py
from django.db import models

# Create your models here.

familybudget/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    slug = models.SlugField(verbose_name=_("Slug"), unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.username)
        super(CustomUser, self).save(*args, **kwargs)

familybudget/apps/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for field_name in ["username", "password1", "password2"]:
            self.fields[field_name].help_text = None

familybudget/apps/budgets/views.py
from django.shortcuts import render

# Create your views here.

familybudget/apps/users/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView

from apps.users.forms import CustomUserCreationForm


class RegisterView(SuccessMessageMixin, UserPassesTestMixin, CreateView):
    form_class = CustomUserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")
    success_message = _("Account was created successfully.")

    def test_func(self):
        return self.request.user.is_anonymous

    def handle_no_permission(self):
        return HttpResponseRedirect(reverse("home"))

familybudget/apps/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block styles %}
    <link href="{% static 'users/css/styles.css' %}" rel="stylesheet">
{% endblock styles %}


{% block content %}
    <div class="form-container">
        {% for message in messages %}
            <p class="alert alert-success text-center" role="alert">{{ message }}</p>
        {% endfor %}
        <form action="" method="post">
            {% csrf_token %}
            <h1>{% translate "Login" %}</h1>
            {{ form|crispy }}
            <input type="submit" value="{% translate 'Log in' %}">
            <h4>{% translate "Don't have an account?" %} <a
                    href="{% url 'users:register' %}">{% translate "Sign up" %}</a></h4>
        </form>
    </div>
{% endblock content %}

familybudget/apps/users/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block styles %}
    <link href="{% static 'users/css/styles.css' %}" rel="stylesheet">
{% endblock styles %}

{% block content %}
    <div class="form-container">
        {% for message in messages %}
            <p class="alert alert-success text-center" role="alert">{{ message }}</p>
        {% endfor %}
        <form action="" method="post">
            {% csrf_token %}
            <h1>{% translate "Create new user" %}</h1>
            {{ form|crispy }}
            <input type="submit" value="{% translate 'Create' %}">
            <h4>{% translate "Already have an account?" %} <a
                    href="{% url 'users:login' %}">{% translate "Log in" %}</a></h4>
        </form>
    </div>
{% endblock content %}

familybudget/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <script src="https://kit.fontawesome.com/d17701c4ad.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    {% block styles %}
    {% endblock styles %}

</head>
<body>
<div class="main">
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">FamilyBudget</a>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">{% translate 'Login' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">{% translate 'Register' %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">{% translate 'Logout' %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container content">
        {% block content %}
        {% endblock content %}
    </div>
</div>
</body>
</html>

{% block scripts %}
{% endblock scripts %}

familybudget/templates/home.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="home-page">
        <h1>{% translate 'This page is in progress...' %}</h1>
    </div>
{% endblock content %}